build_command: |
  echo "🚀 Starting DigitalOcean build process..."
  
  # Install Python dependencies
  echo "📦 Installing Python dependencies..."
  pip install -r backend/requirements.txt
  
  # Install Node.js dependencies
  echo "📦 Installing Node.js dependencies..."
  npm install
  
  # Build frontend
  echo "🔨 Building frontend..."
  npm run build
  
  echo "✅ Build completed successfully!" 