build_command: |
  echo "🚀 Starting DigitalOcean build process..."
  
  # Install Python dependencies only
  echo "📦 Installing Python dependencies..."
  pip install -r backend/requirements.txt
  
  echo "✅ Build completed successfully!" 